# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce6589736541095c25b75b79fdf29898132910f5a1d5a032ee5371a46935e4fe500a81fcdc386aadab07ef8fa7db5eea914edffb950484d97b33d36c4fe9af1f

test:
  secret_key_base: bb1a6d3c2952d2448cc76107ee1eadf6ee8a1a78651552ccd2a041158dd36e995ec1dd48e32603dc58ba83c8fd30f2e0670bcd22ac06f3efbfff80214dae0272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
